import "./globals.css";
import { Inter } from "next/font/google";
import Navbar from "@/components/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Avian Driving School",
  description: "Generated by create next app",
};

const classNames = (...classes) => {
  return classes.filter(Boolean).join(" ");
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={classNames(
          inter.className,
          "antialiased text-gray-900 bg-gray-100 h-full"
        )}
      >
        <Navbar />
        {children}
      </body>
    </html>
  );
}
